### PR TITLE
Update NuMI flux file to latest version

### PR DESCRIPTION
**Pull request by woodtp**
This version of the file contains some changes to the internal structure, and also reflects changes to a bug discovered in PPFX in calculating the feynman-X for interactions of two mesons, which significantly reduced the flux-averaged uncertainty and correlative effects.

Notable changes include:
- Addition of a `ppfx_flux_weights` directory, which contains TH1D for each FHC/RHC neutrino flavor. The histogram bins hold the weight for the particular range of true neutrino energy.
- `fractional_uncertainties/hadron`
  - The inclusive meson uncertainty channel has been further decomposed into projectile/target mesons.

image

### CODE REVIEW

**Comment by woodtp** [comment]
See slides from [this talk](https://indico.fnal.gov/event/59606/contributions/265597/attachments/166570/221916/xf_bugfix.pdf) by @aaduszki for details regarding the bug fix.

**Comment by brucehoward-physics** [comment]
In my own looks using this file and the very related PR https://github.com/SBNSoftware/sbnana/pull/96, I'm noticing a couple things, one of which I want to check if it's expected: the PC1 seems larger than the PC0, is this expected? I see this both in my test using some selection and in your plots in the related PR.

Otherwise, I was able to make some selected plots with flux weights (actually the output looks the same as what I got using you temporary version) and with the beam systs and 5 PCs as a test.

**Comment by woodtp** [comment]
> In my own looks using this file and the very related PR [SBNSoftware/sbnana#96](https://github.com/SBNSoftware/sbnana/pull/96), I'm noticing a couple things, one of which I want to check if it's expected: the PC1 seems larger than the PC0, is this expected? I see this both in my test using some selection and in your plots in the related PR.
> 
> Otherwise, I was able to make some selected plots with flux weights (actually the output looks the same as what I got using you temporary version) and with the beam systs and 5 PCs as a test.

Converting to variances (by squaring the value in each bin) makes it easier to see what is going on with the PCs. Here is a stacked plot of the variance contributions from the first 8 PCs, which accounts for 93.1% of the total variance in the HP covariance matrix:

pcs_variance_composition

PC0 (dark blue) and PC1 (dark orange) describe similar fractions of the total variance (27.0% and 25.5%, respectively). However, a slightly larger fraction of the total variance exists in the HE bins, which is where we find the largest contributions from PC0. In contrast, PC1 is the dominate descriptor of LE bins.

**Comment by brucehoward-physics** [comment]
Thanks for the explanation. Hitting approve.

**Review by brucehoward-physics — APPROVED** [review]

**Comment by brucehoward-physics** [comment]
I am not the expert on all the components of the file, but I confirmed that it worked with the updated systematics in CAFAna in the other PR. So I hit accept.

**Comment by woodtp** [comment]
I've committed a revision to the flux file, because I left out the beam power upgrade systematic. Also, I added a text file with definitions of the covariance matrix bins, which is required by GUNDAM.

**Pull request merged**
