### PR TITLE
New Numi flux systs file. Updated README.

### PR DESCRIPTION
**Pull request by woodtp**

### CODE REVIEW

**Comment by brucehoward-physics** [comment]
Are reviews required on this sort of PR? I don't know the rules regarding these sorts of commits. Tagging @miquelnebot

**Comment by brucehoward-physics** [comment]
@miquelnebot I guess I'm not sure how I'm supposed to review a root file as part of a PR review? [that is to say: is there a best practice guidance or something?]

**Comment by brucehoward-physics** [comment]
@miquelnebot also is there guidance on how we want to archive data products? E.g. this PR removes a ROOT file and adds a new one. Should it instead be tagged as deprecated or old or etc. but kept around? (especially since here the old one is like 10MB supposedly). Really not sure what the best practices are considered to be in this repository... Thanks!

**Comment by brucehoward-physics** [comment]
@miquelnebot That's a request for the submitter right? (@apwood-physics)

**Comment by woodtp** [comment]
@brucehoward-physics 

I discovered that I had omitted some information regarding the PCA in the previous version, or didn't supply it in a very useful format. Primarily, I broke out the components of the PCA according to neutrino mode, as well as transposed the x-axis into bins of neutrino energy (GeV). I also included some supplemental information, such as the eigenvalues/eigenvectors of the input covariance matrix.

image


image

**Comment by brucehoward-physics** [comment]
I left a few notes on the `sbnana` PR that relate to the file, but I also compared just a couple histograms between this ROOT file and the old one (I think from v01_02 because I was a little confused by which version is actually meant to be compared to... Maybe this is part of the answer in the end.)

Anyway, I looked at a couple things between the two:
* I looked at PC0 FHC NuMu and noticed that the shapes were fairly similar though the values in the bins didn't exactly match. Do I understand correctly that things were rerun and so this may be okay? Should others be compared?
* Relatedly, I noticed at least in PC0 FHC NuMu the values were positive before and are now negative. I guess it's probably okay and just means +1 and -1 sigma shift switch meanings between samples, but am bringing it up.
* I looked at Horn Current FHC NuMu and noticed some very different fractional uncertainties between versions, is this expected?

I didn't really look at other histograms...

**Comment by woodtp** [comment]
@miquelnebot I'm closing the PR to include some additionally requested data to this file.

**Pull request closed without merging**
